### ISSUE TITLE
filetype not detected

### ISSUE THREAD

**Issue by choucavalier** [neomutt/neomutt.vim#13]
I have this plugin installed. It correctly detects neomuttrc files most of the time.

However, when I open a file named `~/.config/neomutt/notmuch.neomuttrc` it does not detect the filetype correctly. The filetype is NULL.

What could be going wrong?

**Comment by flatcap** [comment]
The detection is done by the filename.
We check for quite a few possible names, but you've picked a form that we missed:

https://github.com/neomutt/neomutt.vim/blob/2d62568159b4c0fcab27cf6badc6c8b70e049600/ftdetect/neomuttrc.vim#L1

I'll add `*.neomuttrc` to the list, in a second, then you can update your plugin.

If a syntax plugin doesn't recognise your file, you can always configure _your_ vim locally:
```vim
autocmd BufNewFile,BufRead *.neomuttrc setfiletype neomuttrc
```

or manually identify your file with a comment:

```vim
# vim: syntax=neomuttrc
```

(this needs to be in the first few or last few lines)
See: `:help modeline`

**Comment by choucavalier** [comment]
Thanks! Indeed, I think it would be a nice addition to this plugin.

**Comment by flatcap** [comment]
Already done :-)
