### ISSUE TITLE
[docs] tree-sitter

### ISSUE THREAD

**Issue by Freed-Wu** [neomutt/neomutt.vim#16]
I write a tree-sitter grammar. The above is tree-sitter, the below is vim syn. Can it be added to README.md ?

![Screenshot from 2024-02-14 09-50-29](https://github.com/neomutt/mutt-language-server/assets/32936898/51b084c0-e1b3-4e62-be68-f94981853de7)

**Comment by flatcap** [comment]
Hi @Freed-Wu,
I see you're doing lots of things that I don't understand :-)
Keep up the good work!
If you have any questions, or need a hand, just ask.
Thanks!

**Comment by Freed-Wu** [comment]
You are welcome.

Can I have administrator privilege of <https://github.com/neomutt/tree-sitter-lsp>?

This repo is one of two dependencies of [mutt-language-server](https://github.com/neomutt/mutt-language-server) <https://github.com/neomutt/mutt-language-server/blob/main/requirements.txt#L4> (another is <https://github.com/neomutt/tree-sitter-muttrc>) which contains mostly utilities functions required by [mutt-language-server](https://github.com/neomutt/mutt-language-server).

**Comment by flatcap** [comment]
> Can I have administrator privilege of [neomutt/tree-sitter-lsp](https://github.com/neomutt/tree-sitter-lsp)?

Done
